accounting:
  api:
    v1: accounting/v1
exchange:
  host: http://api.exchangerate.host
  api-key: a74a9626514e8e7b5fb7b4e42e7e338c
  converter: /convert?access_key=%s&from=%s&to=%s&amount=%s
  list: /list?access_key=%s
  mock-rate: 0.05
