accounting:
  api:
    v1: accounting/v1
exchange:
  base-url: http://api.exchangerate.host/%s?access_key=%s
  api-key: <api-key>
  convert:
    path: /convert
    query: "&from=%s&to=%s&amount=%s"
    fallback-rates:
      EUR:
        USD: 1.0923192
        GBP: 0.8800000
      USD:
        EUR: 0.9200000
        GBP: 0.8000000
      GBP:
        EUR: 1.1400000
        USD: 1.2500000
  currency:
    path: /list
  mock-rate: 0.05
  mock-currencies: EUR,USD,GBP
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml